name: 'course_advanced_dbt'
version: '1.0.0'
config-version: 2

profile: 'course_advanced_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

log-path: 'logs'
target-path: 'target'
packages-install-path: 'dbt_packages'

clean-targets:
  - "target"
  - "dbt_packages"

models:
  course_advanced_dbt:
    +materialized: view
    +grants:
      select: ['transformer', 'reporter']
seeds:
  dbt_project_evaluator:
    dbt_project_evaluator_exceptions:
      +enabled: false
      
  course_advanced_dbt:
    unit_testing:
      +schema: unit_testing
      +tags: unit_testing
      unit_test_input_dim_dates:
        +column_types:
          CALENDAR_DATE: DATE
          DATE_WEEK: DATE
          DATE_MONTH: DATE
          DATE_QUARTER: DATE
          DATE_YEAR: DATE
          DAY_OF_MONTH: NUMBER(38, 0)
          YEAR_NUM: NUMBER(38, 0)
          QUARTER_NUM: NUMBER(38, 0)
          MONTH_NUM: NUMBER(38, 0)

      unit_test_input_dim_subscriptions:
        +column_types:
          SUBSCRIPTION_ID: NUMBER(38, 0)
          SUBSCRIPTION_PLAN_ID: NUMBER(38, 0)
          USER_ID: NUMBER(38, 0)
          STARTS_AT: TIMESTAMP_NTZ
          ENDS_AT: TIMESTAMP_NTZ
          PLAN_NAME: VARCHAR

      unit_test_output_fct_mrr:
        +column_types:
          SURROGATE_KEY: VARCHAR
          DATE_MONTH: DATE
          USER_ID: NUMBER(38, 0)
          SUBSCRIPTION_ID: NUMBER(38, 0)
          STARTS_AT: TIMESTAMP_NTZ
          ENDS_AT: TIMESTAMP_NTZ
          PLAN_NAME: VARCHAR
          MRR_AMOUNT: FLOAT
          MRR_CHANGE: FLOAT
          RETAINED_MRR_AMOUNT: FLOAT
          PREVIOUS_MONTH_MRR_AMOUNT: FLOAT
          CHANGE_CATEGORY: VARCHAR
          MONTH_RETAINED_NUMBER: NUMBER(38, 0) 
          


  